{
  "vul_id": "VUL4J-2",
  "tests": {
    "overall_metrics": {
      "number_failing": 1,
      "number_passing": 0,
      "number_skipping": 0,
      "number_running": 1,
      "number_error": 0
    }, 
    "skipping_tests": [],
    "passing_tests": [],
    "failures": [
      {
        "failure_name": "java.lang.AssertionError",
        "detail": "Should not try to load external DTD: java.net.ConnectException: Connection refused (Connection refused)", 
        "is_error": false,
        "test_class": "org.apache.batik.dom.util.TestCVE_2017_5662",
        "test_method": "testCVE_2017_5662"
      }
    ]
  }, 
  "benchmark": "vul4j",
  "repository": {
    "name": "apache_batik"
  }
}